### ISSUE TITLE
Skipping forward in video

### ISSUE THREAD

**Issue by mariellem** [antingshen/BeaverDam#105] opened 2017-06-26 20:33 UTC
Using the sample videos, the video player has the feature of allowing the annotator to skip forward to any time in the video (either using the bar or by typing in a time). This feature works for the videos hosted on S3, but for locally-stored videos (such as /video/0) it doesn't work when the video is first loaded - only after the page is refreshed.

Any suggestions as to how I can either fix this or work around it?

**Comment by ankurgupta7** [comment] 2017-07-17 18:03
same issue here except that it does not work even after page reload for longer videos. seek and keyframe click works for original videos. Any help is appreciated. 
UPDATE:
Tried converting vidoes to h264 high profile using the attached scripts and it helped with a 3 minute video. but nothing changed on a 1 hr video changed even after conversion followed by segmentation.

**Comment by antingshen** [comment] 2017-07-17 20:46
Does the video work by itself if you open the video file directly in the browser? That'd be a good place to start

**Comment by ankurgupta7** [comment] 2017-07-18 07:12
yes. the video works in browser. to be clear, the video plays in beaverdam as well. it is the "seek" and "click on keyframes" that does not work.
Reproducing the bug:

1. Add a long video to database. 
2. open webpage for annotating. 
3. annotate on two keyframes.
4. click on frame circular markers below the seek bar. 
5. takes you to begining of video instead of that keyframe
Alternatively:
Drag the seek controller. Hit Play. Takes you to first frame again.

**Comment by clayshieh** [comment] 2017-07-21 02:39
@ankurgupta7 @mariellem I have reproduced the problem. It seems to be a problem with Google Chrome (I am using Version 59.0.3071.115). Play back works correctly on Firefox though so I'd recommend you use Firefox for longer videos. I have verified that views/player.js is working correctly.

**Comment by clayshieh** [comment] 2017-07-25 06:22
@mariellem @ankurgupta7 I looked into the problem further and it turns out that the reason why chrome cant play back bigger files is because chrome always enforces byte serving so that it only loads/buffer what is necessary to start video playback while firefox seems to just download the entire file if the server isn't responding to the range-request header. The reason why the seeded videos worked was because they were only ~1.5MB which, I assume, falls within the size limit of the request. More info can be found [here](https://stackoverflow.com/a/18745164)

I have modified the code to force the browser to download the entire video first before initializing the video player which solves the problem but will mean that the worker has to wait for the entire file to download first before starting which may be problematic or undesired if the file size is very large.

**Comment by clayshieh** [comment] 2017-07-25 17:45
Preloading fix can be found here #107

**Comment by ankurgupta7** [comment] 2017-07-25 18:02
Great! That was a good catch! I'll get back to beaverdam next week and test if this works for me. Appreciate the effort.

**Comment by clayshieh** [comment] 2017-08-15 22:15
So after looking into the numerous possible fixes that could be done we've decided to just document the issue here and leave it up to the user to choose the option that fits their video provider the best. 

There are more or less 3 scenarios and for these 3 scenarios, local server refers to the server hosting the BeaverDam instance while remote server refers to an external server that hosts video content such as aws or youtube.

Scenario 1 - local server hosting big videos. Install Django Whitenoise to serve local content because it supports range requests/byte serving for static media hosted on local server according to [here](https://github.com/evansd/whitenoise/issues/82) but keep in mind that theres a caveat for whitenoise, "For one thing, as described above, it only checks for static files at startup and so files added after the app starts won’t be seen."- [Whitenoise Docs](http://whitenoise.evans.io/en/stable/django.html)
Alternatively you can set up nginx/Apache on your local server to serve these files as they will support the range request headers and doesn't have the caveat that whitenoise does so you can create Video Objects from admin at anytime without having to stop and start your server. This is a good idea if you're planning to deploy the instance into production and hosting your own content.

Scenario 2 - local server hosting only small videos (<2MB depends) videos. Fine nothing needs to be changed from default Beaver Dam but you can also use all the fixes from Scenario 1

Scenario 3 - remote server hosting small or large videos. Fine nothing needs to be changed as video objects may be embedded cross origin as per Same origin policy [specs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) 

**NOTE** the branch/hotfix committed in this branch only works for large/small videos hosted on the local server and **DOES NOT** work for videos hosted on remote servers. If you run it you will see that the embedded videos hot linked from AWS created from the seed script do not work because the XMLHttpRequest used to download the file into the local filesystem is not allowed to download those files due to a CORS issue.

**Closed as completed by clayshieh** 2017-08-15 22:15 UTC
